# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mxl_negll_grad_pref_cpp <- function(X, draws, mean, sdFull, dist, sdPos, obsID, panelID, weights, nObs, nPanel, nPars) {
    .Call(`_logitr_mxl_negll_grad_pref_cpp`, X, draws, mean, sdFull, dist, sdPos, obsID, panelID, weights, nObs, nPanel, nPars)
}

